# Dependencies
markdown:         redcarpet
highligther:      true

# Permalinks
permalink:        pretty

# Setup
title:            Explorer et comprendre l'Univers
tagline:          "Automne 2014"
description:      "Un cours d'introduction à l'astronomie et l'astrophysique"
url:              http://astro.loicseguin.com

author:
  name:           'Loïc Séguin-Charbonneau'
  url:            http://loicseguin.com

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/loicseguin/astronomie
